### ISSUE TITLE
Question about indexDownload and Gratitude

### ISSUE THREAD

**Issue by Alex-SYZ1** [pcdi/ApabiDownloader#1]
This code is  of great use, via my test, in which I have successfully downloaded 3 books. Nevertheless, could you make it capable of  " indexDownload " function? That is, 导出目录功能.
BTW, I'm curious how you change the js code into python code, and whether you have  PKU account so that you develop and test the code via it?
In the end, thank you so much. Your masterpiece helps me a lot.

**Comment by Alex-SYZ1** [comment]
这个代码我使用了很多次，最近发现有一些问题，我在下面具体描述一下：
+ 有时加载速度较慢，甚至出现断连现象，且重启无效,报错如下，不知道是网站问题还是代码问题？
```cmd
Traceback (most recent call last):
  File "C:\Users\26352\.virtualenvs\ApabiDownloader-main-P3b6G0AZ\Lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "C:\Users\26352\.virtualenvs\ApabiDownloader-main-P3b6G0AZ\Lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator     
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\26352\.virtualenvs\ApabiDownloader-main-P3b6G0AZ\Lib\site-packages\scrapy\core\downloader\middleware.py", line 54, in process_request       
    return (yield download_func(request=request, spider=spider))
  File "C:\Users\26352\.virtualenvs\ApabiDownloader-main-P3b6G0AZ\Lib\site-packages\twisted\internet\defer.py", line 892, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "C:\Users\26352\.virtualenvs\ApabiDownloader-main-P3b6G0AZ\Lib\site-packages\scrapy\core\downloader\handlers\http11.py", line 397, in _cb_timeout     
    raise TimeoutError(f"Getting {url} took longer than {timeout} seconds.")
twisted.internet.error.TimeoutError: User timeout caused connection failure: Getting http://apabi.lib.pku.edu.cn/OnLineReader/Command/Getcontent.ashx?OrgIden
tifier=pku&objID=isbn7-301-05853-5.ft.cebx.1&parentIndex=0&ServiceType=getcontent&metaId=ISBNxxxxx&OrgId=pku&SessionId=8EF52317491777CF&cult=US&UserN
ame=%E6%9D%A5%E8%87%AA+10.7.225.197+%E7%9A%84%E7%94%A8%E6%88%B7 took longer than 180.0 seconds..
```
+ 图片内文字错误。
这个问题比较奇怪，在浏览器在线阅读该书籍，每一页都是以图片形式展现；但在您的代码下载到本地的图片中，第一是经常出现简体汉字变为繁体字的情况，第二是数学符号都被识别为乱码。第二种问题尤为致命。问题如下图所示。  
![189](https://github.com/pcdi/ApabiDownloader/assets/117272700/c3cec596-1f93-44ee-b3ed-3af2ab4c13b1)
我很好奇您是如何获取这些图片的？难道是使用了OCR？不然我无法解释为什么下载网页上的图片，会出现图片内不可选中的文字错误问题。之后有空了会仔细拜读您的代码，让我自己在学习爬虫的路上更进一步。今晚我在网上发现了selenium-wire爬取图片方法，处理后能够处理apabi的反爬虫机制，等编写完善后希望能与您交流。  
感谢您！
